workflows:
  maui-android:
    name: MAUI NET8 Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - davidKeystore
      groups:
        - google_play_credentials
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET_BIN: $CM_BUILD_DIR/dotnet
        PACKAGE_NAME: "io.codemagic.mauinet8"
    scripts:
      - name: Install dotnet sdk
        script: | 
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir $DOTNET_PATH
      - name: Install MAUI
        script: | 
          $DOTNET_BIN nuget locals all --clear 
          $DOTNET_BIN workload install maccatalyst
          $DOTNET_BIN workload install maui \
            --source https://aka.ms/dotnet8/nuget/index.json \
            --source https://api.nuget.org/v3/index.json

      - name: Build
        script: |
          LATEST_BUILD_NUMBER=1
          if [ -z $LATEST_BUILD_NUMBER ]; then
              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
              UPDATED_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))
          fi
          $DOTNET_BIN workload list
          $DOTNET_BIN workload update
          $DOTNET_BIN publish -f net8.0-android \
            -c Release \
            -p:AndroidKeyStore=True \
            -p:AndroidSigningKeyStore=$CM_KEYSTORE_PATH \
            -p:AndroidSigningKeyAlias=$CM_KEY_ALIAS \
            -p:AndroidSigningKeyPass=$CM_KEY_PASSWORD \
            -p:AndroidSigningStorePass=$CM_KEYSTORE_PASSWORD \
            -p:ApplicationVersion=$UPDATED_BUILD_NUMBER \
            -p:ApplicationDisplayVersion="1.2" \
            -o ../artifacts
    artifacts:
        - build/**/outputs/**/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true