workflows:
  maui-ios:
    name: MAUI ios
    max_build_duration: 120
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
    integrations:
      app_store_connect: DavidAPIkey
    environment:
      xcode: 16.2
      ios_signing:
        distribution_type: app_store
        bundle_identifier: io.codemagic.mauinet8
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET:  $CM_BUILD_DIR/dotnet/dotnet
        PACKAGE_NAME: "io.codemagic.mauinet8"
    scripts:
        - name: Install dotnet sdk
          script: | 
            wget https://dot.net/v1/dotnet-install.sh
            chmod +x dotnet-install.sh
            ./dotnet-install.sh --channel 8.0 --install-dir $DOTNET_PATH

        - name: Install MAUI iOS workload only
          script: |
            $DOTNET nuget locals all --clear
            $DOTNET workload install maui-ios ios

        # - name: Install MAUI workload
        #   script: | 
        #     $DOTNET nuget locals all --clear 
        #     $DOTNET workload install ios maui \
        #       --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json \
        #       --source https://api.nuget.org/v3/index.json   
        - name: Set Info.plist values
          script: | 
            # Automatically fill out the encryption compliance setting

            PLIST=$CM_BUILD_DIR/src/WeatherTwentyOne/Platforms/iOS/Info.plist
            PLIST_BUDDY=/usr/libexec/PlistBuddy
            $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST 

        - name: Set build version and build the app
          script: | 
            LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID")
            if [ -z $LATEST_BUILD_NUMBER ]; then
              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
            else
              UPDATED_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))
            fi
            
            CERT_NAME=$(keychain list-certificates | jq -r '.[] | .common_name')
            PROFILE_NAME=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" -execdir sh -c '/usr/libexec/PlistBuddy -c "print :Name" /dev/stdin <<< $(security cms -D -i {})' \;)
            
            cd "$(dirname "$(find . -name 'MauiNet8.csproj' | head -n 1)")"

            $DOTNET nuget locals all --clear

            $DOTNET restore MauiNet8.csproj \
              -p:TargetFrameworks=net8.0-ios \
              -p:RuntimeIdentifier=ios-arm64

            $DOTNET publish MauiNet8.csproj \
              -p:TargetFrameworks=net8.0-ios \
              -f net8.0-ios \
              -c Release \
              -r ios-arm64 \
              -p:BuildIpa=True \
              -p:ApplicationDisplayVersion="1.0.0" \
              -p:ApplicationVersion=$UPDATED_BUILD_NUMBER \
              -p:CodesignKey="$CERT_NAME" \
              -p:CodesignProvision="$PROFILE_NAME" \
              -o ../artifacts



    artifacts:
        - /Users/builder/artifacts/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  maui-android:
    name: Maui Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: 3.27.4
      android_signing:
        - davidKeystore
      groups:
        - google_play
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet
        PACKAGE_NAME: "io.codemagic.mauinet8"
    scripts:
      - name: Install dotnet sdk
        script: | 
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 8.0 --install-dir $DOTNET_PATH

      - name: Clean Android SDK packs
        script: |
          rm -rf $DOTNET_PATH/packs/Microsoft.Android.Sdk.Darwin
          rm -rf ~/.nuget/packages/microsoft.android.sdk*

      - name: Install MAUI
        script: |
          $DOTNET nuget locals all --clear
          $DOTNET workload install maui-android\
            --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json \
            --source https://api.nuget.org/v3/index.json

      - name: Restore workloads
        script: |
          $DOTNET workload restore MauiNet8.csproj

      - name: Build
        script: |
          $DOTNET publish MauiNet8.csproj \
            -f net8.0-android \
            -c Release \
            -p:AndroidKeyStore=True \
            -p:AndroidSigningKeyStore=$CM_KEYSTORE_PATH \
            -p:AndroidSigningKeyAlias=$CM_KEY_ALIAS \
            -p:AndroidSigningKeyPass=$CM_KEY_PASSWORD \
            -p:AndroidSigningStorePass=$CM_KEYSTORE_PASSWORD \
            -p:ApplicationVersion=$BUILD_NUMBER \
            -p:ApplicationDisplayVersion="1.0.0" \
            -o ../artifacts

    artifacts:
      - /Users/builder/clone/artifacts/*Signed.aab
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true

